version: '2'

services:
  mysqldb:
    container_name: mariadb
    image: mariadb:10.4.10-bionic
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/data/mariadb:/etc/mysql/conf.d
    - $PWD/my55.cnf:/etc/my.cnf
    - $PWD/temp_my.cnf.j2:/.my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=qazwsx
    - MYSQL_DATABASE=cardb
    - MYSQL_USER=ecuser
    - MYSQL_PASSWORD=qazwsx
    - EXTRA_OPTS="--lower_case_table_names=1"
    - TZ=Asia/Taipei
#    network_mode:  "host"
    user: root
    ports: 
     - "3306:3306" 